def main(): int
{
  const int x = 10;

  x += 20; # throw exception

  return 0;
}
